name: Workflow to buildx jenkins image
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Output Build Number
        run: echo ${{ github.run_number }}

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      
      - name: Export env vars
        run: sh ./vars.sh

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build the image and copy to Dockerhub
        run: |
          docker buildx build --push \
            --tag johannesanchez/jenkins-multiarch:latest \
            --platform linux/amd64,linux/arm/v7 .

      - name: Build the image with build version number and copy to Dockerhub
        run: |
          docker buildx build --push \
            --tag johannesanchez/jenkins-multiarch:$tag_version \
            --platform linux/amd64,linux/arm/v7 .